### ISSUE TITLE
How can I change the number of classes?

### ISSUE THREAD

**Issue by ulanbator** [pjreddie/darknet#1758] opened 2019-08-03 13:46 UTC

**Comment by developer0hye** [comment] 2019-08-05 01:31
refer to [this repo](https://github.com/AlexeyAB/darknet)

**Comment by ulanbator** [comment] 2019-08-05 01:34
Thank you so much.

**Comment by developer0hye** [comment] 2019-08-16 07:03
You should close this issue if the problem is solved!

**Closed** 2019-12-02 13:19 UTC
